modif toto
mickaelhaye/Haye-Mickael-projet-5 pull request #1
Opened 2023-05-05 11:44 UTC by mickaelhaye

2023-05-05 11:45 UTC, vipollet requested changes

2023-05-05 11:45 UTC, vipollet commented on src/main/java/com/safertyNet/safetyNetAlerts/controller/controller.java
> +//toto
Ne pas oublier de supprimer ce commentaire

2023-05-11 12:00 UTC, vipollet requested changes

2023-05-11 12:00 UTC, vipollet commented on src/main/java/com/safertyNet/safetyNetAlerts/controller/Controller.java
> +@Component
Je pense que la meilleure annotation dans le cas d'un controller est @RestController

2023-05-11 12:00 UTC, vipollet commented on src/main/java/service/JsonFileRecup.java
> +@Component
Pour un service, l'annotation @Service est plus appropriée

2023-05-11 12:00 UTC, vipollet commented on src/main/java/service/JsonFileRecup.java
> +public class JsonFileRecup {
Pour le nommage des classes, en général on retrouve le type d'élément en suffixe du nom de classe. Par exemple, si la classe JsonFileRecup est un bean de type service, il convient plutôt de l'appeler JsonFileRecupService.

2023-05-11 12:00 UTC, vipollet commented on src/main/java/service/JsonFileRecup.java
> +		String path = "src/main/resources/data/data.json";
Dans la mesure du possible, étant donné que cette variable n'est pas amenée à changer dans le temps, je pense qu'il est mieux de la définir dans le fichier application.properties 
Ca te permettra aussi de voir comment, avec Spring, récupérer automatiquement le contenu d'une variable  dans un fichier properties :)

2023-05-11 12:00 UTC, vipollet commented on src/main/java/service/JsonFileRecup.java
> +		for (int i = 0; i < liste.size(); i++) {
Avec Jackson, il y a un moyen de récupérer automatiquement une liste d'objets d'un type donné (ici Person en l'occurrence) 
Tu peux t'inspirer de cette doc pour y parvenir : https://www.baeldung.com/jackson-deserialization

2023-05-11 12:00 UTC, vipollet commented on src/main/resources/data/dataold.json
> +{
Est-ce que ce fichier a un intérêt ?

2023-05-11 12:00 UTC, vipollet commented on src/main/resources/data/data (copie).json
> +{
Est-ce que ce fichier a un intérêt ?

2023-05-11 12:00 UTC, vipollet commented on src/main/java/service/JsonFileRecup.java
> +			file.addFirestation(address, station);
Il ne faut pas oublier d'insérer les objets récupérés dans la base de données h2, il faudra donc nécessairement prévoir des opérations de CRUD (Create, read, update, delete) via une classe dédiée (un Repository en Spring)

2023-05-11 12:12 UTC, vipollet requested changes

2023-05-11 12:12 UTC, vipollet commented on src/main/java/com/safertyNet/safetyNetAlerts/SafetyNetAlertsApplication.java
> +public class SafetyNetAlertsApplication implements CommandLineRunner {
Il n'est pas nécessaire d'implémenter le CommandLineRunner dans notre cas. 
Pour effectuer le chargement des données du JSON au lancement de l'application, il vaut mieux utiliser un post constructor (https://www.baeldung.com/running-setup-logic-on-startup-in-spring) dans une classe dédiée, qui sera exécuté au lancement de l'application et qui chargera toutes les données du Json dans notre base de données H2

2023-05-11 12:12 UTC, vipollet commented on src/main/java/com/safertyNet/safetyNetAlerts/SafetyNetAlertsApplication.java
> +	private Controller controller;
Il ne sera pas nécessaire d'injecter le controller, Spring saura le trouver avec l'annotation @RestController

2023-05-11 12:12 UTC, vipollet commented on src/main/java/com/safertyNet/safetyNetAlerts/SafetyNetAlertsApplication.java
> +	@Override
Il ne sera donc pas nécessaire d'implémenter cette méthode non plus

2023-05-12 08:07 UTC, mickaelhaye commented on src/main/java/service/JsonFileRecup.java
> +@Component
ok

2023-05-12 08:10 UTC, mickaelhaye commented on src/main/java/service/JsonFileRecup.java
> +public class JsonFileRecup {
ok

2023-05-12 08:12 UTC, mickaelhaye commented on src/main/java/service/JsonFileRecup.java
> +		String path = "src/main/resources/data/data.json";
Modifiacation mis en place mais ne fonctionne pas

2023-05-12 08:13 UTC, mickaelhaye commented on src/main/resources/data/dataold.json
> +{
ok

2023-05-12 08:13 UTC, mickaelhaye commented on src/main/resources/data/data (copie).json
> +{
ok

2023-05-15 11:35 UTC, mickaelhaye commented on src/main/java/com/safertyNet/safetyNetAlerts/controller/Controller.java
> +@Component
ok

2023-05-15 11:36 UTC, mickaelhaye commented on src/main/java/service/JsonFileRecup.java
> +		String path = "src/main/resources/data/data.json";
ok

2023-05-15 11:36 UTC, mickaelhaye commented on src/main/java/service/JsonFileRecup.java
> +		for (int i = 0; i < liste.size(); i++) {
ok

2023-05-15 11:37 UTC, mickaelhaye commented on src/main/java/com/safertyNet/safetyNetAlerts/SafetyNetAlertsApplication.java
> +public class SafetyNetAlertsApplication implements CommandLineRunner {
ok

2023-05-15 11:37 UTC, mickaelhaye commented on src/main/java/com/safertyNet/safetyNetAlerts/SafetyNetAlertsApplication.java
> +	private Controller controller;
ok

2023-05-15 11:37 UTC, mickaelhaye commented on src/main/java/com/safertyNet/safetyNetAlerts/SafetyNetAlertsApplication.java
> +	@Override
ok

2023-05-15 11:37 UTC, mickaelhaye commented on pom.xml
> +		<dependency>
ok

2023-05-16 11:38 UTC, vipollet approved these changes

2023-05-31 07:32 UTC, vipollet commented on pom.xml
> +    		<groupId>com.h2database</groupId>
Attention à cette dépendance, si tu n'utilises pas H2 dans le projet livré, pense à la retirer, ça peut donner une mauvaise information.

2023-05-31 07:32 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/Controller.java
> +public class Controller {
J'aurais plutôt mis ça dans un service, les Controlleurs doivent servir à décrire les endpoints, or ici il n'y a pas d'endpoint à décrire. Les annotations @RestController et @Data ne sont pas utiles dans ce cas par conséquent (Dans un service, l'annotation @Service sera à privilégier)

2023-05-31 07:32 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/FirestationController.java
> +		logger.info("@GetMapping(value = \"/firestation\")");
Pour les logs au niveau "info", je préfère qu'ils soient plus explicites. Dans le cas présent, c'est un get sur toutes les firestations, tu peux plutôt mettre une phrase (En anglais ou français, peu importe à ce stade) qui explique ce que fait l'endpoint (Par exemple : Récupération de toutes les firestations). Pour les autres endpoints (POST, GET avec des paramètres, tu peux rajouter dans les logs les valeurs de ces paramètres

2023-05-31 07:32 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/FirestationController.java
> +	void majPointeur() {
à voir si cette fonction est utile dans le cas où tu ne réécris pas les données dans le JSON

2023-05-31 07:32 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/model/FirestationModel.java
> +	public FirestationModel(String address, String station) {
Tu peux utiliser l'annotation @AllArgsConstructor plutôt que de définir toi même le constructeur, dans la mesure où tu utilises Lombok dans le projet

2023-05-31 07:32 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/repository/FileEntryRepository.java
> +@Repository
A mon sens, ce n'est pas un Repository Spring, juste un bean qui va te permettre de stocker tes listes d'objet

2023-05-31 07:32 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/repository/JsonFileReadRepository.java
> +@Repository
Idem ici, ce n'est pour moi pas un repository, mais plutôt un service

2023-05-31 07:32 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/repository/JsonFileWriteRepository.java
> +@Repository
Idem ici, ça ressemble plutôt à un service

2023-05-31 15:54 UTC, mickaelhaye commented on pom.xml
> +    		<groupId>com.h2database</groupId>
ok

2023-05-31 15:54 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/controller/Controller.java
> +public class Controller {
ok

2023-06-01 06:45 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/controller/FirestationController.java
> +	void majPointeur() {
ok

2023-06-01 07:34 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/controller/FirestationController.java
> +	void majPointeur() {
ok

2023-06-01 07:34 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/controller/Controller.java
> +public class Controller {
ok

2023-06-01 07:43 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/model/FirestationModel.java
> +	public FirestationModel(String address, String station) {
ok

2023-06-01 07:44 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/repository/FileEntryRepository.java
> +@Repository
comment déclarer un bean

2023-06-01 07:44 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/repository/JsonFileReadRepository.java
> +@Repository
ok

2023-06-01 07:44 UTC, mickaelhaye commented on src/main/java/com/safetynet/safetynetalerts/repository/JsonFileWriteRepository.java
> +@Repository
ok

2023-06-01 19:26 UTC, vipollet requested changes

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/FirestationController.java
> +public class FirestationController {
Un détail, mais j'aurais mis une majuscule à Station (FireStationController)

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/FirestationController.java
> +	@DeleteMapping("/firestation/{stationOrAddress}")
Attention avec ce genre de paramètre qui prend 2 variables potentielles, ça ne respecte pas les standards REST.  Utilise plutôt 2 paramètres optionnels, un pour station, l'autre pour address. Cela aura par conséquent un impact sur le service

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/MedicalrecordController.java
> +	@DeleteMapping("/medicalRecord/{firstNameLastName}")
Idem ici, pour être conforme aux principes REST, mieux vaut utiliser 2 variables obligatoires dans ce cas.

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/firestation/{station}")
Si le chemin est /firestation, j'aurais plutôt mis ça dans le FireStationController

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/firestation/{station}")
Attention également, les documents précisent qu'il faut utiliser un query parameter, or ici tu utilises une path variable. (/firestation?stationNumber=<station_number> et non /firestation/{stationNumber}

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/childAlert/{address}")
Idem ici, il faut utiliser un query param

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/phoneAlert/{station}")
Idem ici, il faut utiliser un query param

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/fire/{address}")
Idem ici, il faut utiliser un query param

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/flood/stations/{station}")
Idem ici, il faut utiliser un query param

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/personInfo/{firstName}")
Idem ici, il faut utiliser un query param

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@GetMapping(value = "/communityEmail/{city}")
Idem ici, il faut utiliser un query param

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/controller/PersonController.java
> +	@DeleteMapping("/person/{firstNameLastName}")
Idem ici, pour être conforme aux principes REST, mieux vaut utiliser 2 variables obligatoires dans ce cas.

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/FileEntryService.java
> +public class FileEntryService {
Ca ressemble plutôt à un bean qu'à un service, je pense qu'il faut le déplacer dans le package model, et utiliser l'annotation @Bean

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/FirestationService.java
> +		for (FirestationModel firestationTest : jsonFileReadRepository.getFile().getFirestations()) {
attention au nommage de la variable (Test)

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/FirestationService.java
> +		for (FirestationModel firestationTest : jsonFileReadRepository.getFile().getFirestations()) {
Idem ici, le nommage n'est pas correct

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/FirestationService.java
> +		logger.debug("deleteFirestation " + stationOrAddress);
Il faudra modifier cette méthode avec l'utilisation des 2 paramètres (Station et Adresse)

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/MedicalRecordService.java
> +		logger.debug("deleteMedicalRecord " + firstNameLastName);
Il faudra modifier cette méthode avec l'utilisation des 2 paramètres (Firstname et Lastname)

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/PersonByAddressService.java
> +public class PersonByAddressService {
Idem sur ce bean, ça ressemble plus à un objet Model qu'à un service (Il n'y a pas de logique métier, juste une représentation d'un objet)

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/PersonByFoyerService.java
> +public class PersonByFoyerService {
Pareil, il s'agit d'un bean et non d'un service.

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/PersonService.java
> +		logger.debug("findByFirestationAListPersons " + station);
Note pour plus tard, essayer de revoir ce traitement en utilisant les streams Java.

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/PersonService.java
> +		logger.debug("deletePerson " + firstNameLastName);
Il faudra modifier cette méthode avec l'utilisation des 2 paramètres (Firstname et Lastname)

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/PersonService.java
> +		logger.debug("deletePerson " + firstNameLastName);
+ utiliser un stream Java pour rechercher l'élément à supprimer

2023-06-01 19:26 UTC, vipollet commented on src/main/java/com/safetynet/safetynetalerts/service/PersonbyFirestationService.java
> +public class PersonbyFirestationService {
Pareil ici, il s'agit d'un bean et non d'un service

2023-06-12 10:27 UTC, closed without merging